.\" Copyright (c) 2021 Aisha Tammy <floss@bsd.ac>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 5 2021 $
.Dt table-ldap_perl 8
.Os
.Sh NAME
.Nm table-ldap_perl
.Nd LDAP backend for OpenSMTPD
.Sh SYNOPSIS
.Nm table-ldap_perl
.Op Fl f Ar config_file
.Sh DESCRIPTION
.Nm
is an table backend for OpenSMTPD, serving the API described in
.Xr table 5 .
The default configuration file is
.Pa /etc/table-ldap_perl.ini .
The configuration file is divided into two major parts, the
.Sy global
configuration section and a
.Sy local
section for each domain.
Unspecified options for a domain are inherited from the
.Sy global
configuration.
.Ss CONFIGURATION OPTIONS
The only difference between global and per-domain configurations options
is that the global options are not under any header.
The following options are available :
.Bl -tag -width Ds -compact
.It Ar server = ldap.example.tld
.Pp
The LDAP domain used for queries.
.Pp
.It Ar admin = cn=admin,dc=example,dc=tld
.Pp
A user who has read permissions for the LDAP tree of the domain.
.Pp
.It Ar password = xxxxxx
.Pp
The LDAP password used by the admin account for binding to the LDAP server.
.Pp
.It Ar users = Users
.Pp
The Organizational Unit in which the users are stored.
.Pp
.It Ar aliases = Aliases
.Pp
The Organizational Unit in which the aliases are stored.
.Pp
.It Ar mail = mail
.Pp
The attribute of a user which has the email address.
.Pp
.It Ar alias = sn
.Pp
The attribute of an alias which points to the real email address.
.Pp
.It Ar name = cn
.Pp
The attribute of an alias which has the aliased email address.
.El
.Sh EXAMPLES
Consider the following LDAP tree:
.Bd -literal -offset width

  .
  |-- dc=example,dc=tld
  |   |-- ou=Users
  |   |   |-- cn=Jane,mail=jane@example.tld
  |   |   |-- cn=John,mail=john@example.tld
  |   |-- ou=Aliases
  |       |-- cn=bossjane@example.tld,sn=jane@example.tld
  |       |-- cn=bossjohn@example.tld,sn=jane@example.tld
  |
  |-- dc=another,dc=xyz
      |-- ou=People
      |   |-- firstName=Jack,mail=jack@another.xyz
      |   |-- firstName=Jade,mail=jade@another.xyz
      |-- ou=Aliases
          |-- cn=bossjack@another.xyz,sn=jack@another.xyz
          |-- cn=bossjade@another.xyz,sn=jade@another.xyz
          |-- cn=bossjane@another.xyz,sn=jane@example.tld

.Ed
